---
title: "Descriptive Statistics"
author: "Abel AUSSANT"
date: "2023-11-02"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(here)
library(lmtest)
library(sandwich)
library(gt)
library(gtsummary)
library(boot)
library(gurobi)
library(MatchIt)
library(cobalt)
library(ggplot2)
library(pwr)
library(survey)
library(smd)
library(weights)
library(ggthemes)


source(here("02_import", "import_bases.R"))

PC18 <- PC18 %>% filter(AGE > 20)
```

# Description of streaming users population

```{r}
theme_gtsummary_language(language = "en", decimal.mark = ",", big.mark = " ")

PC18_survey <- survey::svydesign(id = ~IDENT18, data = PC18, weights = PC18$POND)
```

## Music streaming

### soc-dem char X streaming music
```{r}
t_stream_music_socdem <- PC18_survey %>%
  subset(!is.na(stream_spe)) %>%
  tbl_svysummary(
    include = c("stream_spe", "AGE", "SEXE_femme", "DIPLOME_eng"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(AGE ~ "Age mean (sd)",
                 SEXE_femme ~ "% women",
                 DIPLOME_eng ~ "Education level"),
    by = stream_spe,
    missing = "ifany",
    missing_text = "N missing",
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0),
                  all_categorical() ~ 0)
  ) %>%
  add_overall(last = T
  ) %>% 
  bold_labels() %>%
  modify_header(update = list(
    all_stat_cols() ~ "**{level}**, N = {n_unweighted}",
    stat_1 ~ gt::html("**Non user**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"),
    stat_2 ~ gt::html("**Streaming user**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"),
    stat_0 ~ gt::html("**All music consumers**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"))) %>%
  modify_footnote(update = everything() ~ NA)

t_stream_music_socdem
```

## Film

### soc-dem X watching film on streaming plateforme

```{r}

t_stream_film_socdem <- PC18_survey %>%
  subset(freq_film != "Jamais") %>%
  tbl_svysummary(
    include = c("film_stream_VOD", "AGE", "SEXE_femme", "DIPLOME_eng"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(AGE ~ "Age mean (sd)",
                 SEXE_femme ~ "% women",
                 DIPLOME_eng ~ "Education level"),
    by = film_stream_VOD,
    missing = "ifany",
    missing_text = "N missing",
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0),
                  all_categorical() ~ 0)
  ) %>%
  add_overall(last = T
  ) %>% 
  bold_labels() %>%
  modify_header(update = list(
    all_stat_cols() ~ "**{level}**, N = {n_unweighted}",
    stat_1 ~ gt::html("**Non user**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"),
    stat_2 ~ gt::html("**Streaming user**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"),
    stat_0 ~ gt::html("**All movies consumers**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"))) %>%
  modify_footnote(update = everything() ~ NA) 

t_stream_film_socdem
```

## Show

### soc-dem X watching show on streaming plateformes

```{r}
t_stream_serie_socdem <- PC18_survey %>%
  subset(freq_serie != "Jamais") %>%
  tbl_svysummary(
    include = c("serie_stream_VOD", "AGE", "SEXE_femme", "DIPLOME_eng"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(AGE ~ "Age mean (sd)",
                 SEXE_femme ~ "% women",
                 DIPLOME_eng ~ "Education level"),
    by = serie_stream_VOD,
    missing = "ifany",
    missing_text = "N missing",
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0),
                  all_categorical() ~ 0)
  ) %>%
  add_overall(last = T
  ) %>% 
  bold_labels() %>%
  modify_header(update = list(
    all_stat_cols() ~ "**{level}**, N = {n_unweighted}",
    stat_1 ~ gt::html("**Non user**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"),
    stat_2 ~ gt::html("**Streaming user**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"),
    stat_0 ~ gt::html("**All series consumers**<br> N = {n_unweighted} <br> {round(p_unweighted * 100, 0)} %"))) %>%
  modify_footnote(update = everything() ~ NA) 

t_stream_serie_socdem
```


## The three together

```{r}
tbl_all_stream_socdem <-
  tbl_merge(
    tbls = list(t_stream_music_socdem, t_stream_film_socdem, t_stream_serie_socdem),
    tab_spanner = c("**Music**", "**Movies**", "**Series**")
  ) %>%
  as_gt() %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")


tbl_all_stream_socdem
```

