---
title: "Comparasion echantillion maitre et échantillion d'auditeur de musique"
author: "Abel AUSSANT"
date: '2022-07-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(here)
library(gtsummary)
library(questionr)
library(gt)
library(survey)

source(here("02_import", "import_bases.R"))

theme_gtsummary_language("fr", decimal.mark = ",", big.mark = " ")

PC18_survey <- survey::svydesign(id = ~IDENT18, data = PC18, weights = PC18$POND)

PC18_prat_survey <- subset(PC18_survey, music_12m != "Jamais")

```

# Comparaison entre l'echantillon maitre et l'echantillon des individus écoutant de la musique

```{r}
tab_maitre <- PC18_survey %>%
  tbl_svysummary(
    include = c("SEXE_r", "AGE_r", "DIPLOME_r", "PCS_MENAGE"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(SEXE_r ~ "Sexe",
                 AGE_r ~ "Age",
                 DIPLOME_r ~ "Niveau de diplôme",
                 PCS_MENAGE ~ "PCS ménage"),
    missing = "ifany",
    statistic = list(all_categorical() ~ "{p} %"),
    digits = list(all_categorical() ~ c(0,0))
  ) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_header(update = list(stat_0 ~ html("N = {N_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  bold_labels() 


#echnatillon pratiquant

tab_pratiquant <- PC18_prat_survey %>%
  tbl_svysummary(
    include = c("SEXE_r", "AGE_r", "DIPLOME_r", "PCS_MENAGE"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(SEXE_r ~ "Sexe",
                 AGE_r ~ "Age",
                 DIPLOME_r ~ "Niveau de diplôme",
                 PCS_MENAGE ~ "PCS ménage"),
    missing = "ifany",
    statistic = list(all_categorical() ~ "{p} %"),
    digits = list(all_categorical() ~ c(0,0))
  ) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_header(update = list(stat_0 ~ html("N = {N_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  bold_labels()




tbl_comp_echant <-
  tbl_merge(
    tbls = list(tab_maitre, tab_pratiquant),
    tab_spanner = c("**Echantillon maître**", "**Echantillon pratiquant**")
  ) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enquête Pratiques culturelles des français 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br> Champ : Fran?ais ag?s de plus de 15 et plus.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tbl_comp_echant

```

