---
title: "Description resultats analyse géométriques"
author: "Abel AUSSANT"
date: '2022-07-07'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(questionr)
library(FactoMineR)
library(Factoshiny)
library(factoextra)
library(tidyverse)
library(GDAtools)
library(nleqslv)
library(nnet)
library(missMDA)
library(explor)
library(gtsummary)
library(gt)
library(survey)
library(here)

source(here("02_import", "import_bases.R"))

theme_gtsummary_language("fr", decimal.mark = ",", big.mark = " ")

PC18_survey <- survey::svydesign(id = ~IDENT18, data = PC18, weights = PC18$POND)

PC18_prat_survey <- subset(PC18_survey, music_12m != "Jamais")

```

# description des axes de l'ACM sur les goûts

```{r}
#### desccription des axes ####
#Cr?ation de deux dataframe contenant les varables de description des axes, axe 1 et 2.

coord_axes <- as.data.frame(res.MCA$var[["coord"]])
contrib_axes <- as.data.frame(res.MCA$var[["contrib"]])

#axe 1
mean_contrib_axe1 <- mean(contrib_axes$`Dim 1`)

desc_axe1 <- coord_axes
desc_axe1$coord <- desc_axe1$`Dim 1`
desc_axe1$contrib <- contrib_axes$`Dim 1`
desc_axe1 <- subset(desc_axe1, select=c(coord,contrib))
desc_axe1 <- desc_axe1[order(desc_axe1$contrib, decreasing = T),]
desc_axe1 <- subset(desc_axe1, contrib > mean_contrib_axe1)
desc_axe1 <- round(desc_axe1[,],2)
desc_axe1 <- rownames_to_column(desc_axe1, "mod")

desc_axe1_positive <- subset(desc_axe1, coord > 0)
desc_axe1_negative <- subset(desc_axe1, coord < 0)


tab_axe_1_pos <- gt(desc_axe1_positive) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black") %>%
  cols_label(
    mod = md("**Modalité**"),
    coord = md("**Coordonnée**"),
    contrib = md("**Contribution**")) 

tab_axe_1_pos

tab_axe_1_neg <- gt(desc_axe1_negative) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black") %>%
  cols_label(
    mod = md("**Modalité**"),
    coord = md("**Coordonnée**"),
    contrib = md("**Contribution**")) 

tab_axe_1_neg

#axe 2

mean_contrib_axe2 <- mean(contrib_axes$`Dim 2`)

desc_axe2 <- coord_axes
desc_axe2$coord <- desc_axe2$`Dim 2`
desc_axe2$contrib <- contrib_axes$`Dim 2`
desc_axe2 <- subset(desc_axe2, select=c(coord,contrib))
desc_axe2 <- desc_axe2[order(desc_axe2$contrib, decreasing = T),]
desc_axe2 <- subset(desc_axe2, contrib > mean_contrib_axe2)
desc_axe2 <-round(desc_axe2[,],2)
desc_axe2 <- rownames_to_column(desc_axe2, "mod")

desc_axe2_positive <- subset(desc_axe2, coord > 0)
desc_axe2_negative <- subset(desc_axe2, coord < 0)

tab_axe_2_pos <- gt(desc_axe2_positive) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black") %>%
  cols_label(
    mod = md("**Modalité**"),
    coord = md("**Coordonnée**"),
    contrib = md("**Contribution**")) 

tab_axe_2_pos

tab_axe_2_neg <- gt(desc_axe2_negative) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black") %>%
  cols_label(
    mod = md("**Modalité**"),
    coord = md("**Coordonnée**"),
    contrib = md("**Contribution**")) 

tab_axe_2_neg

```

# description classes CAH

## styles écouté

```{r}
tab_ecoute <- PC18_prat_survey %>%
  tbl_svysummary(
    include = c("E1001", "E1002", "E1003", "E1004", "E1005", "E1006", "E1007", 
                "E1008", "E1009", "E1010", "E1011", "E1012", "E1013"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(E1001 ~ "Variété française",
                 E1002 ~ "Musique du monde",
                 E1003 ~ "Musique traditionnelle",
                 E1004 ~ "Variété internationnale",
                 E1005 ~ "RnB",
                 E1006 ~ "Electro/techno",
                 E1007 ~ "Hip hop/rap",
                 E1008 ~ "Metal/Hard rock",
                 E1009 ~ "Pop/rock",
                 E1010 ~ "Jazz",
                 E1011 ~ "Opera",
                 E1012 ~ "Musique classique",
                 E1013 ~ "Autre(s) genre(s) de musique"),
    by = cluster_gout_music, #La variale avec laquelle on croise les donn?es qui ira en colonne
    statistic = list(all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0))) %>%
  add_p(test = list(all_continuous() ~ "svy.t.test",
                    all_categorical() ~ "svy.chisq.test")) %>%
  modify_header(label = "**Ecoute :**",
                update = list(all_stat_cols() ~ html("**{level}**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Khi-2",
                                all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enqu?te pratique culturelles des fran?ais 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br>Champ : R?sidants en France ?g?s de plus de 15 ans d?clarant ?couter de la musique.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tab_ecoute
```

## styles aimé

```{r}
tab_aime <- PC18_prat_survey %>%
  tbl_svysummary(
            include = c("E1201", "E1202", "E1203", "E1204", "E1205", "E1206", "E1207", 
                "E1208", "E1209", "E1210", "E1211", "E1212", "E1213"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(E1201 ~ "Variété française",
                 E1202 ~ "Musique du monde",
                 E1203 ~ "Musique traditionnelle",
                 E1204 ~ "Variété internationnale",
                 E1205 ~ "RnB",
                 E1206 ~ "Electro/techno",
                 E1207 ~ "Hip hop/rap",
                 E1208 ~ "Metal/Hard rock",
                 E1209 ~ "Pop/rock",
                 E1210 ~ "Jazz",
                 E1211 ~ "Opera",
                 E1212 ~ "Musique classique",
                 E1213 ~ "Autre(s) genre(s) de musique"),
    by = cluster_gout_music, #La variale avec laquelle on croise les donn?es qui ira en colonne
    statistic = list(all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0))) %>%
  add_p(test = list(all_continuous() ~ "svy.t.test",
                    all_categorical() ~ "svy.chisq.test")) %>%
  modify_header(label = "**Ecoute :**",
                update = list(all_stat_cols() ~ html("**{level}**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Khi-2",
                                all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enqu?te pratique culturelles des fran?ais 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br>Champ : R?sidants en France ?g?s de plus de 15 ans d?clarant ?couter de la musique.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tab_aime
```


## styles détestés 

```{r}
tab_det <- PC18_prat_survey %>%
  tbl_svysummary(
    include = c("E1301", "E1302", "E1303", "E1304", "E1305", "E1306", "E1307", 
                "E1308", "E1309", "E1310", "E1311", "E1312", "E1313"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(E1301 ~ "Variété française",
                 E1302 ~ "Musique du monde",
                 E1303 ~ "Musique traditionnelle",
                 E1304 ~ "Variété internationnale",
                 E1305 ~ "RnB",
                 E1306 ~ "Electro/techno",
                 E1307 ~ "Hip hop/rap",
                 E1308 ~ "Metal/Hard rock",
                 E1309 ~ "Pop/rock",
                 E1310 ~ "Jazz",
                 E1311 ~ "Opera",
                 E1312 ~ "Classique",
                 E1313 ~ "Autre(s) genre(s) de musique"),
    by = cluster_gout_music, #La variale avec laquelle on croise les donn?es qui ira en colonne
    statistic = list(all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0))) %>%
  add_p(test = list(all_continuous() ~ "svy.t.test",
                    all_categorical() ~ "svy.chisq.test")) %>%
  modify_header(label = "**Ecoute :**",
                update = list(all_stat_cols() ~ html("**{level}**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Khi-2",
                                all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enqu?te pratique culturelles des fran?ais 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br>Champ : R?sidants en France ?g?s de plus de 15 ans d?clarant ?couter de la musique.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tab_det
```

## Moyenne nbr styles

```{r}
tab_mean <- PC18_prat_survey %>%
  tbl_svysummary(
    include = c("nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste", "cluster_gout_music"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles écoutés",
                 nbr_genre_aime ~ "Styles particuliérement aimés",
                 nbr_genre_deteste ~ "Styles particuliérement détestés"),
    by = cluster_gout_music, #La variale avec laquelle on croise les donn?es qui ira en colonne
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))) %>%
  add_p(test = list(all_continuous() ~ "svy.kruskal.test",
                    all_categorical() ~ "svy.chisq.test")) %>%
  modify_header(label = "**Nombre de :**",
                update = list(all_stat_cols() ~ html("**{level}**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Kruskal-Wallis",
                                all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enqu?te pratique culturelles des fran?ais 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br>Champ : R?sidants en France ?g?s de plus de 15 ans d?clarant ?couter de la musique.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tab_mean
```

## Quelques modes d'écoute et musique pour elle même

```{r}
tab_mode <- PC18_prat_survey %>%
  tbl_svysummary(
    include = c("stream_all", "radio", "cd_ou_cass", "vinyle", "music_ellememe"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(stream_all ~ "Sur les plateformes de streaming",
                 radio ~ "A la radio",
                 cd_ou_cass ~ "Sur CD ou cassette",
                 vinyle ~ "Sur vinyle",
                 music_ellememe ~ "\"pour elle-même\", sans rien faire d'autre"),
    by = cluster_gout_music, #La variale avec laquelle on croise les donn?es qui ira en colonne
    statistic = list(all_categorical() ~ "{p} %"),
    digits = list(all_continuous() ~ c(0,0))) %>%
  add_p(test = list(all_continuous() ~ "svy.t.test",
                    all_categorical() ~ "svy.chisq.test")) %>%
  modify_header(label = "**Ecoute de la musique :**",
                update = list(all_stat_cols() ~ html("**{level}**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Khi-2",
                                all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enqu?te pratique culturelles des fran?ais 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br>Champ : R?sidants en France ?g?s de plus de 15 ans d?clarant ?couter de la musique.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tab_mode
```

# Socio-démo

```{r}
tab_demo <- PC18_prat_survey %>%
  tbl_svysummary(
    include = c( "SEXE_r", "AGE", "diplome_3p", "cluster_gout_music", "PCS_MENAGE"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(SEXE_r ~ "Sexe",
                 AGE ~ "Age moyen",
                 diplome_3p ~ "Diplome en 3 postes",
                 PCS_MENAGE ~ "Cat?gorie socioprofessionelle"),
    by = cluster_gout_music, #La variale avec laquelle on croise les donn?es qui ira en colonne
    statistic = list(all_categorical() ~ "{p} %",
                     all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(0,0))) %>%
  add_p(test = list(all_continuous() ~ "svy.kruskal.test",
                    all_categorical() ~ "svy.chisq.test")) %>%
  modify_header(label = "**Ecoute de la musique :**",
                update = list(all_stat_cols() ~ html("**{level}**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Khi-2",
                                all_stat_cols() ~ "Effectifs non pondérés.")) %>%
  as_gt() %>%
  tab_source_note(source_note = html("Source : Enqu?te pratique culturelles des fran?ais 2018. Donn?es pond?r?es pour les pourcentages.
                                     <br>Champ : R?sidants en France ?g?s de plus de 15 ans d?clarant ?couter de la musique.
                                     <br>Lecture : ")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

tab_demo
```