---
title: "Outputs class specific"
author: "Abel AUSSANT"
date: '2023-09-21'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(here)
library(lmtest)
library(sandwich)
library(gt)
library(gtsummary)
library(boot)
library(gurobi)
library(MatchIt)
library(cobalt)
library(ggplot2)
library(pwr)
library(survey)
library(smd)
library(weights)
library(ggthemes)


source(here("02_import", "import_bases.R"))
```


```{r}
# Performing matching
source(here("03_scripts", "matching_music_class_specific.R"))

#Upper class
PC18_to_m_music_upper_survey <- survey::svydesign(id = ~IDENT18, data = PC18_to_m_music_upper %>% 
                                              mutate(stream_spe = as.factor(stream_spe)), 
                                            weights = PC18_to_m_music_upper$POND)


PC18_m_music_upper_survey <- survey::svydesign(id = ~IDENT18, data = PC18_m_music_upper %>% 
                                           mutate(stream_spe = as.factor(stream_spe)), 
                                         weights = PC18_m_music_upper$POND_m)

#middle class
PC18_to_m_music_middle_survey <- survey::svydesign(id = ~IDENT18, data = PC18_to_m_music_middle %>% 
                                              mutate(stream_spe = as.factor(stream_spe)), 
                                            weights = PC18_to_m_music_middle$POND)


PC18_m_music_middle_survey <- survey::svydesign(id = ~IDENT18, data = PC18_m_music_middle %>% 
                                           mutate(stream_spe = as.factor(stream_spe)), 
                                         weights = PC18_m_music_middle$POND_m)

# Working class
PC18_to_m_music_working_survey <- survey::svydesign(id = ~IDENT18, data = PC18_to_m_music_working %>% 
                                              mutate(stream_spe = as.factor(stream_spe)), 
                                            weights = PC18_to_m_music_working$POND)


PC18_m_music_working_survey <- survey::svydesign(id = ~IDENT18, data = PC18_m_music_working %>% 
                                           mutate(stream_spe = as.factor(stream_spe)), 
                                         weights = PC18_m_music_working$POND_m)
```

#Evaluating quality of matching

## Upper class

```{r}
tab_eval_music <- bal.tab(res_match_template_stream_music_upper, binary = "std", thresholds = c(m = 0.2))

tab_eval_music

allvar_mod <- c("SEXE_r_Homme",
                "AGE_5_r_15 - 20",
                "AGE_5_r_21 - 25",
                "AGE_5_r_26 - 30",
                "AGE_5_r_31 - 35",
                "AGE_5_r_36 - 40",
                "AGE_5_r_41 - 45",
                "AGE_5_r_46 - 50",
                "AGE_5_r_51 - 55",
                "AGE_5_r_56 - 60",
                "AGE_5_r_61 - 65",
                "AGE_5_r_66 - 70",
                "AGE_5_r_71 - 75",
                "AGE_5_r_76 - 80",
                "AGE_5_r_81+",
                "CRITREVENU_r_6000 ou plus",
                "CRITREVENU_r_De 1000 à 1199",
                "CRITREVENU_r_De 1200 à 1499",
                "CRITREVENU_r_De 1500 à 1999",
                "CRITREVENU_r_De 2000 à 2499",
                "CRITREVENU_r_De 2500 à 2999",
                "CRITREVENU_r_De 3000 à 3999",
                "CRITREVENU_r_De 4000 à 5999",
                "CRITREVENU_r_De 800 à 999",
                "CRITREVENU_r_Moins de 800",
                "CRITREVENU_r_Manquant",
                "h_travail_semaine",
                "DIPLOME_r_Inf. Bac",
                "DIPLOME_r_Bac",
                "DIPLOME_r_Bac +2/3",
                "DIPLOME_r_Bac +5",
                "DIPLOME_r_Doctorat",
                "naiss_parents_Deux parents nés à l'étranger",
                "naiss_parents_Deux parents nés en France",
                "naiss_parents_Un des deux parents né à l'étranger",
                "naiss_parents_Manquant",
                "DIPLOME_pere_Bac",
                "DIPLOME_pere_Inf. Bac",
                "DIPLOME_pere_Sup. Bac",
                "DIPLOME_pere_Manquant",
                "CS_pere_Agriculteur",
                "CS_pere_Artisant/commerçant",
                "CS_pere_Autres inactifs",
                "CS_pere_Cadre et prof. intel.",
                "CS_pere_Employé",
                "CS_pere_Ouvrier",
                "CS_pere_Prof. inter.",
                "DIPLOME_mere_Bac",
                "DIPLOME_mere_Inf. Bac",
                "DIPLOME_mere_Sup. Bac",
                "DIPLOME_mere_Manquant",
                "sorties_ami_Plusieurs fois/semaine",
                "sorties_ami_Plusieurs fois/mois",
                "sorties_ami_Une fois par mois",
                "sorties_ami_Rarement",
                "sorties_ami_Jamais",
                "VITENCOUPLE_r_Oui, vit dans logement",
                "VITENCOUPLE_r_Oui, vit pas dans logement",
                "VITENCOUPLE_r_Non",
                "logement_Propriétaire (crédit en cours)",
                "logement_Propriétaire (sans crédit)",
                "logement_Usufruitier",
                "logement_Locataire",
                "logement_A titre gratuit",
                "freq_jv_Tous les jours",
                "freq_jv_Une à plusieurs fois/semaine",
                "freq_jv_1 à 3 fois/mois",
                "freq_jv_Plus rarement",
                "freq_jv_Ne joue pas aux JV",
                "freq_tv_Tous les jours",
                "freq_tv_1 à 4 jours/semaine",
                "freq_tv_Plus rarement",
                "freq_tv_Jamais",
                "equip_tv_Mixte",
                "equip_tv_Uniquement écran de TV",
                "equip_tv_Uniquement numérique",
                "clip_tv",
                "equip_film_Mixte",
                "equip_film_Ne regarde pas de film",
                "equip_film_Uniquement écran de TV",
                "equip_film_Uniquement numérique",
                "film_stream_VOD",
                "film_stream_autre",
                "film_DVD",
                "film_num",
                "nbr_genre_film",
                "freq_serie_Tous les jours",
                "freq_serie_Une fois/semaine mini",
                "freq_serie_Une fois/mois mini",
                "freq_serie_Plus rarement",
                "freq_serie_Jamais",
                "equip_serie_Mixte",
                "equip_serie_Uniquement écran de TV",
                "equip_serie_Uniquement numérique",
                "serie_stream_VOD",
                "serie_stream_autre",
                "nbr_genre_serie",
                "info_internet_Ne s'informe pas en ligne",
                "info_internet_Ne suis pas l'actu",
                "info_internet_S'informe en ligne",
                "freq_lecture_Tous les jours",
                "freq_lecture_1/semaine au moins",
                "freq_lecture_1/mois au mois",
                "freq_lecture_Plus rarement",
                "freq_lecture_Ne lit pas",
                "equip_lecture_Mixte",
                "equip_lecture_Ne lit pas de livre",
                "equip_lecture_Uniquement livre papier",
                "equip_lecture_Uniquement numérique ou autre",
                "nbr_genre_film_cine",
                "musee_art_12m",
                "galerie_12m",
                "acces_internet",
                "freq_internet_Tous les jours",
                "freq_internet_Plusieurs fois/semaine",
                "freq_internet_Plus rarement",
                "freq_internet_Jamais",
                "reseaux_sociaux",
                "culture_en_ligne",
                "musique_enfance_Souvent",
                "musique_enfance_De temps en temps",
                "musique_enfance_Rarement",
                "musique_enfance_Jamais",
                "cinema_enfance_Souvent",
                "cinema_enfance_De temps en temps",
                "cinema_enfance_Rarement",
                "cinema_enfance_Jamais",
                "nbr_genre_parent_ecoute",
                "nbr_genre_ecoute_enfance",
                "audivisuel_nonFR",
                "autre_langue")

love_part1 <- love.plot(res_match_template_stream_music_upper, 
                        drop.distance = TRUE, 
                        var.order = "unadjusted",
                        abs = TRUE,
                        thresholds = c(m = .2), 
                        binary = "std",
                        continuous = "std",
                        sample.names = c("Non matché", "Matché"), 
                        title = NULL) +
  xlim(c(0,1)) +
  xlab("Différence de moyenne ou proportion standardisée") +
  ylim(rev(allvar_mod[1:71])) + 
  labs(color = "Echantillon", shape = "Echantillon", size = "Echantillon", group = "Echantillon", stroke = "Echantillon") +
  theme(text = element_text(family = "serif"), axis.text.y = element_text(size = 10))

love_part1

love_part2 <- love.plot(res_match_template_stream_music_upper, 
                        drop.distance = TRUE, 
                        var.order = "unadjusted",
                        abs = TRUE,
                        thresholds = c(m = .2), 
                        binary = "std",
                        continuous = "std",
                        title = NULL) +
  xlab("Différence de moyenne ou proportion standardisée") +
  scale_x_continuous(breaks = seq(0, 1.5, by = 0.25), limits = c(0, 1.5)) +
  ylim(rev(allvar_mod[72:138]))+ 
  labs(color = "Echantillon", shape = "Echantillon", size = "Echantillon", group = "Echantillon", stroke = "Echantillon")+
  theme(text = element_text(family = "serif"), axis.text.y = element_text(size = 10))

love_part2

```

## Middle class

```{r}
tab_eval_music <- bal.tab(res_match_template_stream_music_middle, binary = "std", thresholds = c(m = 0.05))

tab_eval_music

love_part1 <- love.plot(res_match_template_stream_music_middle, 
                        drop.distance = TRUE, 
                        var.order = "unadjusted",
                        abs = TRUE,
                        thresholds = c(m = .05), 
                        binary = "std",
                        continuous = "std",
                        sample.names = c("Non matché", "Matché"), 
                        title = NULL) +
  xlim(c(0,1)) +
  xlab("Différence de moyenne ou proportion standardisée") +
  ylim(rev(allvar_mod[1:71])) + 
  labs(color = "Echantillon", shape = "Echantillon", size = "Echantillon", group = "Echantillon", stroke = "Echantillon") +
  theme(text = element_text(family = "serif"), axis.text.y = element_text(size = 10))

love_part1

love_part2 <- love.plot(res_match_template_stream_music_middle, 
                        drop.distance = TRUE, 
                        var.order = "unadjusted",
                        abs = TRUE,
                        thresholds = c(m = .05), 
                        binary = "std",
                        continuous = "std",
                        title = NULL) +
  xlab("Différence de moyenne ou proportion standardisée") +
  scale_x_continuous(breaks = seq(0, 1.5, by = 0.25), limits = c(0, 1.5)) +
  ylim(rev(allvar_mod[72:138]))+ 
  labs(color = "Echantillon", shape = "Echantillon", size = "Echantillon", group = "Echantillon", stroke = "Echantillon")+
  theme(text = element_text(family = "serif"), axis.text.y = element_text(size = 10))

love_part2

```


## Working class

```{r}
tab_eval_music <- bal.tab(res_match_template_stream_music_working, binary = "std", thresholds = c(m = 0.05))

tab_eval_music

love_part1 <- love.plot(res_match_template_stream_music_working, 
                        drop.distance = TRUE, 
                        var.order = "unadjusted",
                        abs = TRUE,
                        thresholds = c(m = .05), 
                        binary = "std",
                        continuous = "std",
                        sample.names = c("Non matché", "Matché"), 
                        title = NULL) +
  xlim(c(0,1)) +
  xlab("Différence de moyenne ou proportion standardisée") +
  ylim(rev(allvar_mod[1:71])) + 
  labs(color = "Echantillon", shape = "Echantillon", size = "Echantillon", group = "Echantillon", stroke = "Echantillon") +
  theme(text = element_text(family = "serif"), axis.text.y = element_text(size = 10))

love_part1

love_part2 <- love.plot(res_match_template_stream_music_working, 
                        drop.distance = TRUE, 
                        var.order = "unadjusted",
                        abs = TRUE,
                        thresholds = c(m = .05), 
                        binary = "std",
                        continuous = "std",
                        title = NULL) +
  xlab("Différence de moyenne ou proportion standardisée") +
  scale_x_continuous(breaks = seq(0, 1.5, by = 0.25), limits = c(0, 1.5)) +
  ylim(rev(allvar_mod[72:138]))+ 
  labs(color = "Echantillon", shape = "Echantillon", size = "Echantillon", group = "Echantillon", stroke = "Echantillon")+
  theme(text = element_text(family = "serif"), axis.text.y = element_text(size = 10))

love_part2

```

# Outcomes 

## Upper class

```{r}
mean_genre_unm <- PC18_to_m_music_upper_survey %>%
  tbl_svysummary(
    include = c("stream_spe", "nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles musicaux écoutés",
                 nbr_genre_aime ~ "Styles particulièrement aimés",
                 nbr_genre_deteste ~ "Styles detestés"),
    by = stream_spe, #La variale avec laquelle on croise les données qui ira en colonne
    missing = "ifany",
    type = list(nbr_genre_music ~ "continuous",
                nbr_genre_aime ~ "continuous",
                nbr_genre_deteste ~ "continuous"),    
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))
  ) %>%
  add_difference() %>%
  modify_header(label = "**Nombre de :**",
                update = list(stat_1 ~ gt::html("**Non streameur**<br> N = {n_unweighted}"),
                              stat_2 ~ gt::html("**Streameur**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Student.",
                                all_stat_cols() ~ "Effectifs non pondérés."))


mean_genre_m <- PC18_m_music_upper_survey %>%
  tbl_svysummary(
    include = c("stream_spe", "nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles musicaux écoutés",
                 nbr_genre_aime ~ "Styles particulièrement aimés",
                 nbr_genre_deteste ~ "Styles detestés"),
    by = stream_spe, #La variale avec laquelle on croise les données qui ira en colonne
    missing = "ifany",
    type = list(nbr_genre_music ~ "continuous",
                nbr_genre_aime ~ "continuous",
                nbr_genre_deteste ~ "continuous"),
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))
  ) %>%
  add_difference() %>%
  modify_header(label = "**Nombre de :**",
                update = list(stat_1 ~ gt::html("**Non streameur**<br> N = {n_unweighted}"),
                              stat_2 ~ gt::html("**Streameur**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Student.",
                                all_stat_cols() ~ "Effectifs non pondérés."))

t_comp_m <- tbl_merge(
  tbls = list(mean_genre_unm, mean_genre_m),
  tab_spanner = c("**Echantillon non matché**", "**Echantillon matché**")
) %>% as_gt() %>%
  tab_footnote(
    footnote = "Moyenne et écart type pondérés.",
    locations = cells_body(columns = stat_1_1,
                           rows = 1)
  ) %>%
  tab_source_note(source_note = gt::html("<p align=\"justify\" style=\"
    margin: 0;\"><u>Source</u> : Enquête Pratique culturelles des français 2018.
                                     <br><u>Champ</u> : Résidant en France agés de 15 ans et plus, déclarant écouter de la musique.
                                     <br><u>Lecture</u> : Dans l'échantillon non matché, c'est-à-dire dans la population générale minorée des individus n'écoutant pas de musique, on observe que les non-utilisateurs de plateformes de streaming spécialisées écoutent en moyenne 3,8 (écart-type 2,2) genres musicaux différents. Ceux qui pratiquent l'écoute en streaming déclarent eux écouter 5 styles musicaux différents en moyenne (écart-type 2,5).
                                     <br> Dans la population matchée en revanche, on observe des écarts beaucoup plus faibles. Ainsi, quand on raisonne toutes choses égales par ailleurs, les non-streameurs écoutent 4,8 styles musicaux différents en moyenne (écart-type 2,5), alors que les streameurs en écoutent 5 (écart-type 2,5).</p>")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

t_comp_m
```

## Middle class

```{r}
mean_genre_unm <- PC18_to_m_music_middle_survey %>%
  tbl_svysummary(
    include = c("stream_spe", "nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles musicaux écoutés",
                 nbr_genre_aime ~ "Styles particulièrement aimés",
                 nbr_genre_deteste ~ "Styles detestés"),
    by = stream_spe, #La variale avec laquelle on croise les données qui ira en colonne
    missing = "ifany",
    type = list(nbr_genre_music ~ "continuous",
                nbr_genre_aime ~ "continuous",
                nbr_genre_deteste ~ "continuous"),    
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))
  ) %>%
  add_difference() %>%
  modify_header(label = "**Nombre de :**",
                update = list(stat_1 ~ gt::html("**Non streameur**<br> N = {n_unweighted}"),
                              stat_2 ~ gt::html("**Streameur**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Student.",
                                all_stat_cols() ~ "Effectifs non pondérés."))


mean_genre_m <- PC18_m_music_middle_survey %>%
  tbl_svysummary(
    include = c("stream_spe", "nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles musicaux écoutés",
                 nbr_genre_aime ~ "Styles particulièrement aimés",
                 nbr_genre_deteste ~ "Styles detestés"),
    by = stream_spe, #La variale avec laquelle on croise les données qui ira en colonne
    missing = "ifany",
    type = list(nbr_genre_music ~ "continuous",
                nbr_genre_aime ~ "continuous",
                nbr_genre_deteste ~ "continuous"),
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))
  ) %>%
  add_difference() %>%
  modify_header(label = "**Nombre de :**",
                update = list(stat_1 ~ gt::html("**Non streameur**<br> N = {n_unweighted}"),
                              stat_2 ~ gt::html("**Streameur**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Student.",
                                all_stat_cols() ~ "Effectifs non pondérés."))

t_comp_m <- tbl_merge(
  tbls = list(mean_genre_unm, mean_genre_m),
  tab_spanner = c("**Echantillon non matché**", "**Echantillon matché**")
) %>% as_gt() %>%
  tab_footnote(
    footnote = "Moyenne et écart type pondérés.",
    locations = cells_body(columns = stat_1_1,
                           rows = 1)
  ) %>%
  tab_source_note(source_note = gt::html("<p align=\"justify\" style=\"
    margin: 0;\"><u>Source</u> : Enquête Pratique culturelles des français 2018.
                                     <br><u>Champ</u> : Résidant en France agés de 15 ans et plus, déclarant écouter de la musique.
                                     <br><u>Lecture</u> : Dans l'échantillon non matché, c'est-à-dire dans la population générale minorée des individus n'écoutant pas de musique, on observe que les non-utilisateurs de plateformes de streaming spécialisées écoutent en moyenne 3,8 (écart-type 2,2) genres musicaux différents. Ceux qui pratiquent l'écoute en streaming déclarent eux écouter 5 styles musicaux différents en moyenne (écart-type 2,5).
                                     <br> Dans la population matchée en revanche, on observe des écarts beaucoup plus faibles. Ainsi, quand on raisonne toutes choses égales par ailleurs, les non-streameurs écoutent 4,8 styles musicaux différents en moyenne (écart-type 2,5), alors que les streameurs en écoutent 5 (écart-type 2,5).</p>")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

t_comp_m
```

## Working class

```{r}
mean_genre_unm <- PC18_to_m_music_working_survey %>%
  tbl_svysummary(
    include = c("stream_spe", "nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles musicaux écoutés",
                 nbr_genre_aime ~ "Styles particulièrement aimés",
                 nbr_genre_deteste ~ "Styles detestés"),
    by = stream_spe, #La variale avec laquelle on croise les données qui ira en colonne
    missing = "ifany",
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))
  ) %>%
  add_difference() %>%
  modify_header(label = "**Nombre de :**",
                update = list(stat_1 ~ gt::html("**Non streameur**<br> N = {n_unweighted}"),
                              stat_2 ~ gt::html("**Streameur**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Student.",
                                all_stat_cols() ~ "Effectifs non pondérés."))


mean_genre_m <- PC18_m_music_working_survey %>%
  tbl_svysummary(
    include = c("stream_spe", "nbr_genre_music", "nbr_genre_aime", "nbr_genre_deteste"), #L'ensemble des variables que l'on veut dans le tableau
    label = list(nbr_genre_music ~ "Styles musicaux écoutés",
                 nbr_genre_aime ~ "Styles particulièrement aimés",
                 nbr_genre_deteste ~ "Styles detestés"),
    by = stream_spe, #La variale avec laquelle on croise les données qui ira en colonne
    missing = "ifany",
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(all_continuous() ~ c(1,1))
  ) %>%
  add_difference() %>%
  modify_header(label = "**Nombre de :**",
                update = list(stat_1 ~ gt::html("**Non streameur**<br> N = {n_unweighted}"),
                              stat_2 ~ gt::html("**Streameur**<br> N = {n_unweighted}"))) %>%
  modify_footnote(update = everything() ~ NA) %>%
  modify_footnote(update = list(p.value ~ "Calculé à partir d'un test de Student.",
                                all_stat_cols() ~ "Effectifs non pondérés."))

t_comp_m <- tbl_merge(
  tbls = list(mean_genre_unm, mean_genre_m),
  tab_spanner = c("**Echantillon non matché**", "**Echantillon matché**")
) %>% as_gt() %>%
  tab_footnote(
    footnote = "Moyenne et écart type pondérés.",
    locations = cells_body(columns = stat_1_1,
                           rows = 1)
  ) %>%
  tab_source_note(source_note = gt::html("<p align=\"justify\" style=\"
    margin: 0;\"><u>Source</u> : Enquête Pratique culturelles des français 2018.
                                     <br><u>Champ</u> : Résidant en France agés de 15 ans et plus, déclarant écouter de la musique.
                                     <br><u>Lecture</u> : Dans l'échantillon non matché, c'est-à-dire dans la population générale minorée des individus n'écoutant pas de musique, on observe que les non-utilisateurs de plateformes de streaming spécialisées écoutent en moyenne 3,8 (écart-type 2,2) genres musicaux différents. Ceux qui pratiquent l'écoute en streaming déclarent eux écouter 5 styles musicaux différents en moyenne (écart-type 2,5).
                                     <br> Dans la population matchée en revanche, on observe des écarts beaucoup plus faibles. Ainsi, quand on raisonne toutes choses égales par ailleurs, les non-streameurs écoutent 4,8 styles musicaux différents en moyenne (écart-type 2,5), alors que les streameurs en écoutent 5 (écart-type 2,5).</p>")) %>%
  opt_table_font(font = "Times New Roman") %>%
  tab_options(table_body.hlines.color = "black", source_notes.border.bottom.color = "black", table_body.border.bottom.color = "black",
              table_body.border.top.color = "black", row_group.border.top.color = "black", row_group.border.bottom.color = "black",
              heading.border.bottom.color = "black", column_labels.border.top.color = "black",  table.border.top.color = "black",
              table.border.bottom.color = "black", column_labels.border.bottom.color = "black")

t_comp_m
```



